#!/usr/bin/env bash

if [ "$1" == "" ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

version=$1

for a in `cat mirror-list`; do
    echo $a
    curl -s $a/iso/release/ | fgrep $version &> /dev/null
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "Missing $version release"
    fi
done
