#!/usr/bin/env bash

for a in `cat mirrors.source | fgrep '| http:' | awk '{print $2}'`; do
    echo $a
    curl -s $a/iso/release/ | fgrep 1.0.5 &> /dev/null
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "Missing 1.0.5 release"
    fi
done
